### ISSUE TITLE
Control adjacent event visibility or "depth" with CSS z-index

### ISSUE THREAD

**Issue by Digital-Grinnell** [SummittDweller/hugo-timeline#2]
Avoid having one event obscure or hide another adjacent event.  Since event descriptions appear at the top of the event's display, establish a rule setting the deepest z-index for the most recent event "to" date, and give each earlier event a progressively shallower z-index based on their "to" date.

**Comment by SummittDweller** [comment]
Resolved.  See corresponding section in the `README.md` file.
